Repository devfile/docs, pull requests merged in 2020-11, with the labels that each got.

#20 [WIP]: Fixed broken link
  docs/modules/ROOT/pages/assembly_making-a-workspace-portable-using-a-devfile.adoc
Labels: do-not-merge/work-in-progress, lgtm

#21 Updated specs
  docs/modules/ROOT/partials/proc_writing-a-devfile-for-your-project.adoc
Labels: lgtm

#23 Update node-setup in main.yaml.
  .github/workflows/main.yaml
Labels: bug, documentation, lgtm

#24 Update gh-pages-deploy and other GH actions.
  .github/workflows/main.yaml
Labels: bug, dependencies, documentation, lgtm

#22 Update migration guide.
  docs/modules/ROOT/pages/migration_guide.adoc
Labels: lgtm
