Repository devfile/docs, pull requests merged in 2021-11, with the labels that each got.

#107 fix parent reference example
  docs/modules/user-guide/partials/proc_referring-to-a-parent-devfile-in-a-devfile.adoc
Labels: lgtm

#110 fix parent reference examples
  docs/modules/user-guide/partials/proc_refering-to-a-parent-devfile-in-a-devfile.adoc
Labels: lgtm

#103 Modified gulpfile to fix antora build error
  .gitignore
Labels: documentation, lgtm

#99 added devfile registry content
  docs/modules/user-guide/nav.adoc
  docs/modules/user-guide/pages/adding-a-registry-schema.adoc
  docs/modules/user-guide/pages/building-a-custom-devfile-registry.adoc
  docs/modules/user-guide/pages/deploying-a-devfile-registry.adoc
  docs/modules/user-guide/pages/devfile-registry.adoc
  docs/modules/user-guide/pages/understanding-a-devfile-registry.adoc
  docs/modules/user-guide/partials/assembly_devfile-registry.adoc
  docs/modules/user-guide/partials/con_understanding-a-devfile-registry.adoc
  docs/modules/user-guide/partials/proc_adding-a-registry-schema.adoc
  docs/modules/user-guide/partials/proc_building-a-devfile-registry.adoc
  docs/modules/user-guide/partials/proc_creating-a-git-repository.adoc
  docs/modules/user-guide/partials/proc_deploying-a-devfile-registry-with-helm-chart.adoc
  docs/modules/user-guide/partials/proc_deploying-a-devfile-registry-with-olm.adoc
  docs/modules/user-guide/partials/proc_tagging-and-pushing-a-registry-container-image.adoc
Labels: documentation, lgtm

#112 cherry picked registry docs additions for 2.1
  docs/modules/user-guide/attachments/api-reference/2.1.0/main.css.map
  docs/modules/user-guide/nav.adoc
  docs/modules/user-guide/pages/adding-a-registry-schema.adoc
  docs/modules/user-guide/pages/building-a-custom-devfile-registry.adoc
  docs/modules/user-guide/pages/deploying-a-devfile-registry.adoc
  docs/modules/user-guide/pages/devfile-registry.adoc
  docs/modules/user-guide/pages/understanding-a-devfile-registry.adoc
  docs/modules/user-guide/partials/assembly_devfile-registry.adoc
  docs/modules/user-guide/partials/con_understanding-a-devfile-registry.adoc
  docs/modules/user-guide/partials/proc_adding-a-registry-schema.adoc
  docs/modules/user-guide/partials/proc_building-a-devfile-registry.adoc
  docs/modules/user-guide/partials/proc_creating-a-git-repository.adoc
  docs/modules/user-guide/partials/proc_deploying-a-devfile-registry-with-helm-chart.adoc
  docs/modules/user-guide/partials/proc_deploying-a-devfile-registry-with-olm.adoc
  docs/modules/user-guide/partials/proc_tagging-and-pushing-a-registry-container-image.adoc
Labels: documentation, lgtm

#108 organized procedure into multiple sections
  docs/modules/user-guide/nav.adoc
  docs/modules/user-guide/pages/adding-a-command-group-to-a-devfile.adoc
  docs/modules/user-guide/pages/adding-a-command-section-to-a-devfile.adoc
  docs/modules/user-guide/pages/adding-commands-to-a-devfile.adoc
  docs/modules/user-guide/pages/adding-composite-commands-to-a-devfile.adoc
  docs/modules/user-guide/pages/adding-exec-commands-to-a-devfile.adoc
  docs/modules/user-guide/pages/devfile-commands.adoc
  docs/modules/user-guide/partials/assembly_adding-commands-to-a-devfile.adoc
  docs/modules/user-guide/partials/proc_adding-a-command-group-to-a-devfile.adoc
  docs/modules/user-guide/partials/proc_adding-a-command-section-to-a-devfile.adoc
  docs/modules/user-guide/partials/proc_adding-commands-to-a-devfile.adoc
  docs/modules/user-guide/partials/proc_adding-composite-commands-to-a-devfile.adoc
  docs/modules/user-guide/partials/proc_adding-exec-commands-to-a-devfile.adoc
  docs/modules/user-guide/partials/ref_devfile-commands.adoc
Labels: documentation
