Repository devfile/docs, pull requests merged in 2021-12, with the labels that each got.

#111 added section for devfile library
  docs/modules/user-guide/nav.adoc
  docs/modules/user-guide/pages/devfile-library.adoc
  docs/modules/user-guide/pages/using-the-devfile-library-schema.adoc
  docs/modules/user-guide/pages/using-the-devfile-library.adoc
  docs/modules/user-guide/partials/assembly_devfile-library.adoc
  docs/modules/user-guide/partials/proc_using-the-devfile-library.adoc
Labels: documentation

#114 Fix: name in version switch
  .github/workflows/preview.yaml
  .htmltest.yml
  antora-playbook-for-development.yml
  docs/antora.yml
  gulpfile.js
  supplemental-ui/partials/header-content.hbs
Labels: lgtm

#115 Cherrypick library into 2.1
  docs/modules/user-guide/attachments/api-reference/2.1.0/main.css.map
  docs/modules/user-guide/nav.adoc
  docs/modules/user-guide/pages/devfile-library.adoc
  docs/modules/user-guide/pages/using-the-devfile-library-schema.adoc
  docs/modules/user-guide/pages/using-the-devfile-library.adoc
  docs/modules/user-guide/partials/assembly_devfile-library.adoc
  docs/modules/user-guide/partials/proc_using-the-devfile-library.adoc
Labels: documentation, lgtm

#117 CI: Refactor surge action to deploy preview docs
  .github/workflows/preview-build.yml
  .github/workflows/preview-deploy.yml
  .github/workflows/preview-start.yml
  .github/workflows/preview.yaml
Labels: lgtm

#116 specified that devfiles are yaml files in the authoring stacks docs
  docs/modules/user-guide/nav.adoc
  docs/modules/user-guide/pages/authoring-devfiles.adoc
  docs/modules/user-guide/pages/authoring-stacks.adoc
  docs/modules/user-guide/pages/using-devfiles.adoc
  docs/modules/user-guide/pages/using-stacks.adoc
  docs/modules/user-guide/partials/assembly_authoring-devfiles.adoc
  docs/modules/user-guide/partials/assembly_authoring-stacks.adoc
  docs/modules/user-guide/partials/assembly_using-devfiles.adoc
  docs/modules/user-guide/partials/assembly_using-stacks.adoc
Labels: documentation

#118 cherrypick authoringstacks
  docs/modules/user-guide/nav.adoc
  docs/modules/user-guide/pages/authoring-devfiles.adoc
  docs/modules/user-guide/pages/authoring-stacks.adoc
  docs/modules/user-guide/pages/using-devfiles.adoc
  docs/modules/user-guide/pages/using-stacks.adoc
  docs/modules/user-guide/partials/assembly_authoring-devfiles.adoc
  docs/modules/user-guide/partials/assembly_authoring-stacks.adoc
  docs/modules/user-guide/partials/assembly_using-devfiles.adoc
  docs/modules/user-guide/partials/assembly_using-stacks.adoc
Labels: documentation, lgtm
