Repository devfile/docs, pull requests merged in 2021-09, with the labels that each got.

#91 Update UI to be consistent with the landing-page and registry-viewer
  README.md
  supplemental-ui/css/extra.css
  supplemental-ui/favicon.ico
  supplemental-ui/img/devfile-logo.png
  supplemental-ui/img/devfile-logo.svg
  supplemental-ui/partials/header-content.hbs
Labels: lgtm

#88 TOC restructure
  docs/modules/user-guide/nav.adoc
  docs/modules/user-guide/pages/using-stacks.adoc
  docs/modules/user-guide/partials/assembly_authoring-stacks.adoc
  docs/modules/user-guide/partials/assembly_using-stacks.adoc
Labels: documentation, lgtm

#93 cherry pick toc restructure to 2.1 branch
  docs/modules/user-guide/nav.adoc
  docs/modules/user-guide/pages/using-stacks.adoc
  docs/modules/user-guide/partials/assembly_authoring-stacks.adoc
  docs/modules/user-guide/partials/assembly_using-stacks.adoc
Labels: documentation, lgtm

#83 Change license to Apache 2.0
  LICENSE
Labels: lgtm

#98 Cherry pick registry docs for 2.1
  docs/modules/user-guide/pages/devfile-registry.adoc
  docs/modules/user-guide/partials/con_devfile-registry.adoc
Labels: documentation
