Repository devfile/docs, pull requests merged in 2021-04, with the labels that each got.

#43 Modified docs to adhere to schema_1st PR
  docs/modules/user-guide/partials/proc_adding-a-name-to-a-devfile.adoc
  docs/modules/user-guide/partials/proc_adding-commands-to-a-devfile.adoc
  docs/modules/user-guide/partials/proc_adding-event-bindings.adoc
  docs/modules/user-guide/partials/proc_adding-kubernetes-component-to-a-devfile.adoc
  docs/modules/user-guide/partials/proc_adding-plugin-component-to-a-devfile.adoc
  docs/modules/user-guide/partials/proc_adding-projects-to-a-devfile.adoc
  docs/modules/user-guide/partials/proc_defining-endpoints.adoc
  docs/modules/user-guide/partials/proc_defining-environment-variables.adoc
  docs/modules/user-guide/partials/proc_specifying-persistent-storage.adoc
Labels: documentation

#44 Modified docs to adhere to schema_2nd PR
  docs/modules/user-guide/partials/proc_adding-attributes-to-a-devfile.adoc
  docs/modules/user-guide/partials/proc_adding-container-component-to-a-devfile.adoc
  docs/modules/user-guide/partials/proc_refering-to-a-parent-devfile-in-a-devfile.adoc
Labels: documentation

#45 Modified docs to adhere to schema_3rd PR
  docs/modules/user-guide/partials/proc_defining-kubernetes-resources.adoc
  docs/modules/user-guide/partials/proc_limiting-resources-usage.adoc
  docs/modules/user-guide/partials/proc_migrating-components.adoc
Labels: documentation

#46 Modified docs to adhere to schema_4th PR
  docs/modules/user-guide/partials/proc_migrating-commands.adoc
  docs/modules/user-guide/partials/proc_migrating-plug-ins.adoc
Labels: documentation, lgtm

#49 Removed plugin component
  docs/modules/user-guide/nav.adoc
Labels: documentation, lgtm

#41 added more content and context to devfile resources
  docs/modules/user-guide/partials/ref_devfile-samples.adoc
Labels: documentation, lgtm

#51 Made docs adhere to style guide
  docs/modules/user-guide/nav.adoc
  docs/modules/user-guide/partials/assembly_migrating-to-devfile-v2.adoc
  docs/modules/user-guide/partials/proc_adding-event-bindings.adoc
  docs/modules/user-guide/partials/proc_migrating-commands.adoc
  docs/modules/user-guide/partials/proc_migrating-components.adoc
  docs/modules/user-guide/partials/proc_migrating-plug-ins.adoc
  docs/modules/user-guide/partials/proc_migrating-projects.adoc
  docs/modules/user-guide/partials/proc_migrating-schema-version.adoc
  docs/modules/user-guide/partials/proc_referring-to-a-parent-devfile-in-a-devfile.adoc
Labels: documentation, lgtm

#52 Remove an empty file
  docs/modules/ROOT/pages/migration_guide.adoc
Labels: lgtm

#53 included odo yaml samples in devfile authoring docs
  docs/modules/user-guide/partials/proc_adding-a-name-to-a-devfile.adoc
  docs/modules/user-guide/partials/proc_adding-projects-to-a-devfile.adoc
  docs/modules/user-guide/partials/proc_adding-schema-version-to-a-devfile.adoc
Labels: documentation, lgtm
