Repository devfile/docs, pull requests merged in 2021-06, with the labels that each got.

#74 fix: fix format of samples for git projects
  docs/modules/user-guide/partials/proc_adding-projects-to-a-devfile.adoc
Labels: lgtm

#66 Modified language so it better adheres to IBM style guide
  docs/modules/user-guide/partials/proc_adding-attributes-to-a-devfile.adoc
  docs/modules/user-guide/partials/proc_adding-commands-to-a-devfile.adoc
  docs/modules/user-guide/partials/proc_adding-event-bindings.adoc
Labels: documentation, lgtm

#67 Modified language to adhere better to IBM style guide
  docs/modules/user-guide/partials/proc_adding-container-component-to-a-devfile.adoc
  docs/modules/user-guide/partials/proc_limiting-resources-usage.adoc
  docs/modules/user-guide/partials/proc_referring-to-a-parent-devfile-in-a-devfile.adoc
  docs/modules/user-guide/partials/proc_specifying-persistent-storage.adoc
Labels: documentation, lgtm

#68 Modified language to better adhere to IBM style guide
  docs/modules/user-guide/partials/proc_defining-endpoints.adoc
  docs/modules/user-guide/partials/proc_defining-environment-variables.adoc
  docs/modules/user-guide/partials/proc_defining-kubernetes-resources.adoc
Labels: documentation, lgtm

#65 Modified content to adhere better to IBM style guide
  docs/modules/user-guide/partials/assembly_authoring-stacks.adoc
  docs/modules/user-guide/partials/proc_adding-a-name-to-a-devfile.adoc
  docs/modules/user-guide/partials/proc_adding-projects-to-a-devfile.adoc
Labels: documentation

#73 Added devfile registry docs
  docs/modules/user-guide/nav.adoc
  docs/modules/user-guide/pages/devfile-registry.adoc
  docs/modules/user-guide/partials/con_devfile-registry.adoc
Labels: documentation, lgtm
